---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::{{aws.accountID}}:role/{{aws.clusterRootRoleName}}
  mapUsers: |
    []
