#!/usr/bin/env bash

DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )" 
cd $DIR/$1

# args=$(cat args)
# for each line in args file, run filedo with the line as argument

while read -r argline; do
  echo "Running: $argline"
  if [ -x "$(command -v stack)" ]; then
    stack run -- $argline
  else
    filedo $argline
  fi
done < args

