name: lint
on: 
  pull_request:
  push:
    branches:
      - master
  
jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/hlint-setup@v2
      
      - uses: haskell/actions/hlint-run@v2
        with:
          version: 3.5 # addresses the issue: https://github.com/haskell/actions/issues/128
          path: '["src/", "app/", "test/"]'
          fail-on: warning
