name: lint
on: 
  pull_request:
  push:
    branches:
      - master
  
jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v1
      - uses: haskell/actions/hlint-run@v2
        with:
          path: '["src/", "app/", "test/"]'
          fail-on: warning
          args: --color --report=src/