name: release
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build"]
    types: [completed]

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    name: release
    runs-on: ubuntu-latest
    steps:  
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: latest-builds
          path: bin

      - name: untar linux executable
        run: tar -xzf bin/filedo-Linux-X64.tar.gz -C bin

      - name: version
        run: echo "version=$(./bin/filedo --version)" >> $GITHUB_OUTPUT
        id: version

      - name: add version to artefact names
        run: |
          mv bin/filedo-Linux-X64.tar.gz bin/filedo-Linux-X64-${{ steps.version.outputs.version }}.tar.gz
          mv bin/filedo-MacOS-X64.tar.gz bin/filedo-MacOS-X64-${{ steps.version.outputs.version }}.tar.gz
          mv bin/filedo-Windows-X64.zip bin/filedo-Windows-X64-${{ steps.version.outputs.version }}.zip

      - uses: actions/checkout@v3
        with:
          ref: refs/tags/v${{ steps.version.outputs.version }}

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.1
        with:
          version: ${{ steps.version.outputs.version }}
          validation_level: warn
          validation_depth: 1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          files: |
            bin/filedo-Linux-X64-${{ steps.version.outputs.version }}.tar.gz
            bin/filedo-MacOS-X64-${{ steps.version.outputs.version }}.tar.gz
            bin/filedo-Windows-X64-${{ steps.version.outputs.version }}.zip
          fail_on_unmatched_files: true
